name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (eg 1.2.3 or v1.2.3)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip modules directory
        run: |
          cd modules
          zip -r ../IlluminateDatabaseLib.zip .
          cd ..
          # Ensure file is completely written and verify it exists
          ls -la IlluminateDatabaseLib.zip
          sleep 2

      - name: Create Release and Upload Asset
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: ./IlluminateDatabaseLib.zip
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}