name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (eg, 1.2.3)'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip modules directory
        run: |
          cd modules
          zip -r ../IlluminateDatabaseLib.zip .
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: IlluminateDatabaseLib.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
